### ISSUE TITLE
Initialize nlp4ss repo from template

### ISSUE THREAD

**Issue by entelecheia** [entelecheia/nlp4ss#1]
## Description:

We need to initialize a new repo for the "NLP for Social Science" course by customizing the course-template-i18n template with the project-specific details.

To do this, we'll run the `reinit-project` command from the template repo after updating the `.copier-config.yaml` file with the nlp4ss project info.

## Steps:

1. Fork the course-template-i18n repo to your personal GitHub account.
2. Clone your forked repo locally.
3. Update the `.copier-config.yaml` file with the following nlp4ss project details:

   ```yaml
   author: Your Name
   copyright_year: 2023
   documentation_url: https://yourusername.github.io/nlp4ss
   email: your@email.com
   friendly_name: NLP for Social Science
   github_repo_name: nlp4ss
   github_username: yourusername
   google_analytics_id: your-ga-id
   package_name: nlp4ss
   project_description: A course on applying natural language processing (NLP) techniques for social science research.
   project_name: nlp4ss
   project_short_description: NLP for Social Science
   ```

4. Commit the updated .copier-config.yaml file.
5. Run make reinit-project to re-initialize the repo with nlp4ss project details.
6. Review the changes and create a new repo on GitHub.com
7. Push the customized repo to the new GitHub repo.

This will create a new repo with all the template files and structure customized for the "NLP for Social Science" course.
